import type { Request, Response } from 'express';
import prisma from '../config/prisma.js';

export const generateImage = async (req: Request, res: Response) => {
  try {
    const { prompt, topic = 'general', subject = 'general' } = req.body;

    if (!prompt) {
      return res.status(400).json({ error: 'Prompt is required' });
    }

    // Purge any legacy blurry non-SVG cached images
    await prisma.cachedImage.deleteMany({
      where: { source: { not: 'gemini-svg' } }
    }).catch(() => {});

    // 1. Check Cache (Only use cached images generated by gemini-svg)
    const cachedImage = await prisma.cachedImage.findFirst({
      where: {
        source: 'gemini-svg',
        keywords: {
          has: prompt.toLowerCase().trim()
        }
      }
    });

    if (cachedImage) {
      // Increment usage count
      await prisma.cachedImage.update({
        where: { id: cachedImage.id },
        data: { usageCount: cachedImage.usageCount + 1 }
      });

      return res.status(200).json({
        imageUrl: cachedImage.imageUrl,
        cached: true
      });
    }

    // 2. Check if prompt is a photo request vs an educational visual/diagram request
    const isPhotoRequest = /\b(photo|photograph|real picture|camera picture|real-world photo)\b/i.test(prompt);

    const geminiKey = process.env.GEMINI_API_KEY;

    // 3. GEMINI VECTOR ENGINE: Generate 100% crisp vector SVG graphics for educational diagrams/schematics/anatomy
    if (geminiKey && !isPhotoRequest) {
      try {
        console.log("[ImageController] Using Gemini Vector Engine for SVG graphic generation...");
        const svgSystemInstruction = `You are a master vector graphic illustrator and educational diagram designer.
Generate clean, valid, standalone 16:9 widescreen SVG code (viewBox="0 0 1280 720" width="1280" height="720") illustrating the student's request.

Rules:
1. DESIGN & STYLE:
   - Use a modern flat vector design with crisp container cards on a clean background.
   - Determine an appropriate and aesthetically pleasing color palette dynamically based on the subject matter (e.g., tech-blue for computer science, green/earth tones for biology, warm colors for history). Do not use random hardcoded colors.
   - Draw rounded rectangular blocks (<rect rx="12">), container cards, pointer lines/arrows (<path d="..." stroke-width="3">), or biological/abstract shapes (<path>).
2. TEXT & LABELS:
   - Include clear, bold, highly legible English labels using <text> elements with clean sans-serif fonts.
   - For Computer Science: draw container boxes representing elements/code blocks with clear text callouts.
   - For Biology/Anatomy: draw labeled vector organs/cells/structures with pointer lines and bold text names.
   - For Math/Physics/Flowcharts: draw labeled step boxes and arrows.
   - For Abstract Concepts (e.g., "game mechanics", "learning strategies"): generate a conceptual flowchart or diagram with related visual icons, connected boxes, and descriptive text placeholders illustrating the concept.
3. OUTPUT FORMAT (CRITICAL):
   - You MUST output ONLY valid raw SVG code starting with <svg> and ending with </svg>.
   - NEVER output conversational text, explanations, or refusals.
   - Do NOT include markdown code fences (\`\`\`xml or \`\`\`svg), HTML wrappers, or any conversational text.

User Request: "${prompt}"`;

        const geminiRes = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=${geminiKey}`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{ parts: [{ text: svgSystemInstruction }] }],
            generationConfig: { temperature: 0.2, maxOutputTokens: 3000 }
          })
        });

        if (geminiRes.ok) {
          const geminiJson: any = await geminiRes.json();
          let rawText = geminiJson.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || "";
          
          // Clean backticks or wrappers if present
          rawText = rawText.replace(/^```(xml|svg)?/i, '').replace(/```$/i, '').trim();
          
          const svgMatch = rawText.match(/<svg[\s\S]*<\/svg>/i);
          if (svgMatch) {
            const svgContent = svgMatch[0];
            const base64Svg = Buffer.from(svgContent).toString('base64');
            const dataUrl = `data:image/svg+xml;base64,${base64Svg}`;

            console.log("[ImageController] Gemini Vector SVG generated successfully!");

            // Save to Cache
            await prisma.cachedImage.create({
              data: {
                topic,
                subject,
                imageUrl: dataUrl,
                source: 'gemini-svg',
                keywords: [prompt.toLowerCase().trim()]
              }
            });

            return res.status(200).json({
              imageUrl: dataUrl,
              cached: false
            });
          }
        }
      } catch (svgErr) {
        console.error("[ImageController] Gemini SVG Engine failed, falling back to Pollinations:", svgErr);
      }
    }

    // 4. FALLBACK ENGINE: Pollinations SANA / FLUX for Photo Requests or Fallback
    let finalPrompt = `Modern flat vector educational graphic diagram, conceptual flowchart style, no humans, no characters, high resolution: ${prompt}`;
    if (geminiKey) {
      try {
        const polishInstruction = `Summarize this user request into a concise 1-sentence prompt for a 2D flat vector educational graphic. Ensure the prompt explicitly describes an educational diagram, chart, or conceptual layout. Do NOT include humans or characters. User Request: "${prompt}"`;
        const geminiRes = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=${geminiKey}`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{ parts: [{ text: polishInstruction }] }],
            generationConfig: { temperature: 0.2, maxOutputTokens: 100 }
          })
        });
        if (geminiRes.ok) {
          const geminiJson: any = await geminiRes.json();
          const polishedText = geminiJson.candidates?.[0]?.content?.parts?.[0]?.text?.trim();
          if (polishedText) finalPrompt = `Educational flowchart graphic, abstract concepts, no humans, no characters: ${polishedText}`;
        }
      } catch { /* ignore fallback error */ }
    }

    const seed = Math.floor(Math.random() * 1000000);
    let pollinationsUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(finalPrompt)}?model=sana&width=1280&height=720&nologo=true&seed=${seed}`;

    let response = await fetch(pollinationsUrl);

    if (!response.ok) {
      pollinationsUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(finalPrompt)}?model=flux&width=1280&height=720&nologo=true&seed=${seed}`;
      response = await fetch(pollinationsUrl);
    }

    if (!response.ok) {
      console.error('Pollinations API Error:', response.statusText);
      return res.status(500).json({ error: 'Failed to generate image from Pollinations' });
    }

    const arrayBuffer = await response.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    const mimeType = response.headers.get('content-type') || 'image/jpeg';
    const dataUrl = `data:${mimeType};base64,${buffer.toString('base64')}`;

    // 3. Save to Cache
    await prisma.cachedImage.create({
      data: {
        topic,
        subject,
        imageUrl: dataUrl,
        source: 'pollinations',
        keywords: [prompt.toLowerCase().trim()]
      }
    });

    return res.status(200).json({
      imageUrl: dataUrl,
      cached: false
    });

  } catch (error: any) {
    console.error('Error generating image:', error);
    return res.status(500).json({ error: 'Internal server error' });
  }
};
